Jenkins benchmarking
RobDickinson/pmemkv-tools pull request #37
Opened 2020-11-17 12:08 UTC by karczex

- [ ] c++ Code formatting (clang-format?) 
- [ ] Make libpmemobj++ to be moving part, configurable in configuration json - the same way as pmemkv 
- [ ] Optionally allow to pass configuration json via jenkins interface - what do you think?
- [ ] Add README

2020-11-17 13:25 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 0 of 11 files reviewed, 11 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 21 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLDGrSAATOH0S9Pyc0:-MMLDGrTEYUJRBjpPn44:bbhvzal) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L21)):*
> ```Python
>         self.dir = tempfile.mkdtemp()
>         self.url = config["repo_url"]
>         self.commit = config["commit"]
> ```

that's not necessarily have to be a "commit" it may be branch or tag, I'm guessing
___
*[run_benchmark.py, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLLNbO46zO_mpAcOxq:-MMLLNbO46zO_mpAcOxr:b-60uet) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L43)):*
> ```Python
> 
>         self.path = repo.dir
>         self.pmemkv_path = pmemkv_repo.dir
> ```

what for do you need this `pmemkv_path` ?
___
*[run_benchmark.py, line 51 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLHjR22fIe7jpZhXdS:-MMLHjR22fIe7jpZhXdT:b1lwhwj) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L51)):*
> ```Python
>     def build(self):
>         library_path = self.pmemkv.get_path("libpmemkv.so.1")
>         include_path = self.pmemkv.get_path("libpmemkv.hpp")
> ```

perhaps make these 2 magic strings a const on top of this file
___
*[run_benchmark.py, line 57 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLEnCd8kZBhLMJ2L0H:-MMLEnCd8kZBhLMJ2L0I:bny7i8e) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L57)):*
> ```Python
>             "PATH": os.environ["PATH"],
>         }
>         self.logger.debug(f"{build_env}=")
> ```

is this some crazy f-string syntax to produce `build_env=${build_env}` ? if yes - that's cool :wink:  if no, pls fix, I guess :stuck_out_tongue: :smile: 
___
*[run_benchmark.py, line 138 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLCkHQ8EFIo_bkbRlx:-MMLCkHR5kh4UqLKb8o4:b-kzruop) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L138)):*
> ```Python
>     LOGLEVEL = os.environ.get("LOGLEVEL") or "INFO"
>     lvl = {"DEBUG": logging.DEBUG, "INFO": logging.INFO}
>     logging.basicConfig(level=lvl[LOGLEVEL])
> ```

do you know what exact ver. of python you're running this on? from 3.2 it should work to pass loglevel as a string, so this dict wouldn't be necessary.
___
*[run_benchmark.py, line 175 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLLdPY55M7XtOe8bMA:-MMLLdPY55M7XtOe8bMB:b-g7jpr5) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L175)):*
> ```Python
>     benchmark_results = benchmark.get_results()
> 
>     raport = {key: config[key] for key in config}
> ```

did you mean `report` ?
___
*[run_benchmark.py, line 183 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLLt8c3PPVRJuDpZu1:-MMLLt8c3PPVRJuDpZu2:b-ve3yvb) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L183)):*
> ```Python
>     except pymongo.errors as e:
>         logger.error(f"Cannot upload results to database: {e}")
>         exit(42)
> ```

:smile: 
___
*[bench_scenarios/local.json, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLKmNACQXUsRmPRKPZ:-MMLKmNACQXUsRmPRKP_:bodrzoy) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/bench_scenarios/local.json#L1)):*
> ```JSON
> {
> ```

if you want to commit these scenarios, consider adding some few words of descriptions on the begging of .json file(s)
___
*[utils/jenkins/Jenkinsfile, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLMGqH7MCd4GF13X1-:-MMLMGqH7MCd4GF13X10:b-u4yyq1) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/utils/jenkins/Jenkinsfile#L4)):*
> ```Groovy
> /* Copyright 2019-2020, Intel Corporation */
> 
> /* Jenkinsfile - Scripts to create pmemkv and pmemkv_matrix jobs - to run with initial jenkins job. */
> ```

update plox
___
*[utils/jenkins/README.md, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLMihG4wvGd0tcFb1q:-MMLMihG4wvGd0tcFb1r:b-2o8i7t) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/utils/jenkins/README.md#L1)):*
> ```Markdown
> # Jenkins Configuration
> ```

maybe put here only very short description what these files are for, and link to full readme in pmemkv repo? This may become out-of-date very quickly ;)
___
*[utils/jenkins/lib/api.groovy, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLMzxj8cKsm8NWICbI:-MMLMzxj8cKsm8NWICbJ:b-rodbwj) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/utils/jenkins/lib/api.groovy#L4)):*
> ```Groovy
> /* Copyright 2019-2020, Intel Corporation */
> 
> /* Jenkinsfile - scripts to create pmemkv and pmemkv_matrix jobs - to run with initial jenkins job. */
> ```

I really hate that we have to copy-paste these jenkins scripts between repos... Not that you have to fix it right now, but we should make some common place for them.


<!-- Sent from Reviewable.io -->

2020-11-17 13:30 UTC, lukaszstolarczuk commented
> * [ ]  Optionally allow to pass configuration json via jenkins interface - what do you think?

passing custom benchmark scenario/config would be really appreciated, especially that we put in there pmemkv_bench params, to specify e.g. which benchmark to run...

2020-11-19 12:23 UTC, karczex commented
___
*[run_benchmark.py, line 21 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLDGrSAATOH0S9Pyc0:-MMQQ2wx8sTSCeO-qS3K:bo5y6h3) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's not necessarily have to be a "commit" it may be branch or tag, I'm guessing
</blockquote></details>

indeed, but name "git_object" seems to be even worse.  Do you have a good name for this parameter? 


<!-- Sent from Reviewable.io -->

2020-11-19 12:23 UTC, karczex commented
___
*[run_benchmark.py, line 138 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLCkHQ8EFIo_bkbRlx:-MMQ_jQQ1_LZZQakJajm:b-tj9on1) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you know what exact ver. of python you're running this on? from 3.2 it should work to pass loglevel as a string, so this dict wouldn't be necessary.
</blockquote></details>

python3.8, as debug f-strings was introduced. Optionally I may step back to 3.5 if you think it's needed.  


<!-- Sent from Reviewable.io -->

2020-11-19 12:27 UTC, karczex commented
___
*[bench_scenarios/local.json, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLKmNACQXUsRmPRKPZ:-MMVTJ0tCeHkX9-KZc3p:b5aeogc) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/bench_scenarios/local.json#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you want to commit these scenarios, consider adding some few words of descriptions on the begging of .json file(s)
</blockquote></details>

json format do not support comments in "non tricky" way.


<!-- Sent from Reviewable.io -->

2020-11-20 08:50 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 0 of 11 files reviewed, 10 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 21 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLDGrSAATOH0S9Pyc0:-MMZpnLJBkPR-aYAmFed:bb7dpnb) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L21)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

indeed, but name "git_object" seems to be even worse.  Do you have a good name for this parameter? 
</blockquote></details>

fair enough, I couldn't find a suitable name as well. git checkout uses `<tree-ish>`, but that's no good ;)
___
*[run_benchmark.py, line 138 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLCkHQ8EFIo_bkbRlx:-MMZq1xCDNjzOEJjuKx0:b-5z59cl) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L138)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

python3.8, as debug f-strings was introduced. Optionally I may step back to 3.5 if you think it's needed.  
</blockquote></details>

if you're running on 3.8 than it should work, shouldn't it? Strings as log levels was introduced in 3.2, so it should still work...?
___
*[bench_scenarios/local.json, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLKmNACQXUsRmPRKPZ:-MMZqBISEa-_wml-JGkJ:b-e1qkiw) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/bench_scenarios/local.json#L1)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

json format do not support comments in "non tricky" way.
</blockquote></details>

och, too bad. Perhaps then, some extra readme file with short descriptions...?


<!-- Sent from Reviewable.io -->

2020-11-26 15:03 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 0 of 15 files reviewed, 10 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[run_benchmark.py, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLLNbO46zO_mpAcOxq:-MN445bn-ATo03IBEoPB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what for do you need this `pmemkv_path` ?
</blockquote></details>

Done.
___
*[run_benchmark.py, line 51 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLHjR22fIe7jpZhXdS:-MN42Xhu3sMjmYIg2EIh:bvgkw8m) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L51)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make these 2 magic strings a const on top of this file
</blockquote></details>

It's not needed any more. I added pkg-config support in makefile instead of this tricky logic.
___
*[run_benchmark.py, line 57 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLEnCd8kZBhLMJ2L0H:-MN42oGx43LgBHYt6FLO:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this some crazy f-string syntax to produce `build_env=${build_env}` ? if yes - that's cool :wink:  if no, pls fix, I guess :stuck_out_tongue: :smile: 
</blockquote></details>

Done.
___
*[run_benchmark.py, line 138 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLCkHQ8EFIo_bkbRlx:-MN42wbfDnkCsxKACOwd:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you're running on 3.8 than it should work, shouldn't it? Strings as log levels was introduced in 3.2, so it should still work...?
</blockquote></details>

Done.
___
*[run_benchmark.py, line 175 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLLdPY55M7XtOe8bMA:-MN43-OkB9EA7UlPc34L:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L175)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you mean `report` ?
</blockquote></details>

Done.
___
*[run_benchmark.py, line 183 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLLt8c3PPVRJuDpZu1:-MN436Hi9QIvveUcjVBH:b-kiodg4) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/run_benchmark.py#L183)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:smile: 
</blockquote></details>

I added exception output formatter, so there is no need for catching all possible exceptions. Instead, just crush application, but with not-so-ugly-output :)
___
*[utils/jenkins/lib/api.groovy, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLMzxj8cKsm8NWICbI:-MN43sh8CQIHQn4e_RpK:b-z2hlgy) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/utils/jenkins/lib/api.groovy#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I really hate that we have to copy-paste these jenkins scripts between repos... Not that you have to fix it right now, but we should make some common place for them.
</blockquote></details>

As we discussed off-line, this will be moved elsewhere.  


<!-- Sent from Reviewable.io -->

2020-11-30 14:25 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 2 of 14 files reviewed, 27 unresolved discussions (waiting on @karczex)

___
*[Makefile, line 13 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MN8f0Gg2GmbxfE-lvwb:-MN8f0Gh-S87CgWGAfnz:b-rfki8w) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/Makefile#L13)):*
> ```Makefile
> 
> bench: reset
> 	
> ```

redundant empty line?
___
*[run_benchmark.py, line 16 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MN8o9cU4AVVJJf2kln_:-MN8o9cU4AVVJJf2klna:bfnf2im) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L16)):*
> ```Python
> logger = logging.getLogger(__name__)
> sys.__excepthook__ = lambda ex_type, ex, traceback: logger.error(
>     f"{ex_type.__name__}: {exception}"
> ```

`exception` -> `ex` ?

side note - did you tested, this hook works?
___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOGjuk4BRb9PWr7iBD:-MNOGjuk4BRb9PWr7iBE:buhgmwf) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
> ```Python
>         self.build_env["PATH"] = os.environ["PATH"]
>         self.cmake_params = config["cmake_params"] + [
>             f"-DCMAKE_INSTALL_PREFIX={self.path}"
> ```

I'm afraid, if you specify an install path in the custom "cmake_params" it will be overwritten by your hard-coded prefix. I believe you can switch the sequence, firstly set your path then add "cmake_params"
___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOKG7h6rt3mBi1Pkxt:-MNOKG7h6rt3mBi1Pkxu:bfv4ob) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
> ```Python
>         self.build_env["PATH"] = os.environ["PATH"]
>         self.cmake_params = config["cmake_params"] + [
>             f"-DCMAKE_INSTALL_PREFIX={self.path}"
> ```

Am I getting this correctly, you're installing in the same directory as the repository's path?
___
*[run_benchmark.py, line 68 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOImK-BL0nKjrCC0GU:-MNOImK-BL0nKjrCC0GV:b-hy96qn) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L68)):*
> ```Python
>         try:
>             subprocess.run(
>                 "cmake .".split() + self.cmake_params,
> ```

this is an in-tree build? is it supported in our repos?
___
*[run_benchmark.py, line 131 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOK_2IEp6IM0FqVWYP:-MNOK_2IEp6IM0FqVWYQ:b-rkw6a3) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L131)):*
> ```Python
>     def get_results(self):
>         OutputReader = csv.DictReader(
>             self.run_output.stdout.decode("UTF-8").split("\n"), delimiter=","
> ```

`\n` - there's no `os.newline` or something to use?
___
*[run_benchmark.py, line 155 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNONfWYBv4rf3GjBsB2:-MNONfWYBv4rf3GjBsB3:b-2yy4th) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L155)):*
> ```Python
>     # Parse arguments
>     parser = argparse.ArgumentParser(description="Runs pmemkv_bench")
>     parser.add_argument("config_path", help="Path to json config file")
> ```

required?
___
*[run_benchmark.py, line 195 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOOVnM1DgtIMByB1ro:-MNOOVnM1DgtIMByB1rp:bopbg5o) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L195)):*
> ```Python
>     if db_address and db_port and db_user and db_passwd and db_name:
>         upload_to_mongodb(db_address, db_port, db_user, db_passwd, db_name, report)
> ```

else: warning/info message
___
*[bench/db_bench.cc, line 188 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOU2Jo5-TjNeFSxul-:-MNOU2Jo5-TjNeFSxul0:b-ozbfn8) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L188)):*
> ```cpp
> 	std::map<std::string, std::string> global_data;
> 	std::set<std::string> column_index;
> 	std::string _id_name = "benchmark";
> ```

I believe, recently Igor found some guidelines, not to start var names with `_` - rename to `id_name_`/`id_name`
___
*[bench/db_bench.cc, line 233 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUbgH-PXBM9V9mSYi:-MNOUbgH-PXBM9V9mSYj:b-nsqcu9) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L233)):*
> ```cpp
> 	void print_histogram()
> 	{
> ```

redundant empty line
___
*[bench/db_bench.cc, line 237 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUf_h9o0QQEvXkw87:-MNOUf_i-5IlFa7yyFG4:basqvae) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L237)):*
> ```cpp
> 		for ( auto &histogram: histograms )
> 		{
> 			std::cout << histogram.first << "\n"  <<  histogram.second.ToString() << std::endl;
> ```

`"\n"` -> `std::endl`
___
*[bench/db_bench.cc, line 268 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUrJl8j4NxFadkdyi:-MNOUrJm7A_--TdFr75f:buy7spa) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L268)):*
> ```cpp
> 			std::cout << "," << column;
> 		}
> 		std::cout << "\r\n";
> ```

std::endl ?
___
*[bench/db_bench.cc, line 296 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUyq_852ikvjoKyu8:-MNOUyq_852ikvjoKyu9:b-twoe9a) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L296)):*
> ```cpp
>         {
>                std::cout << std::left << std::setw(12) << benchmark.first << ": ";
> 		for(auto &result: benchmark.second)
> ```

apply some code style formatting
___
*[bench/db_bench.cc, line 516 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOVG_x6ZwmrSxZNnVz:-MNOVG_x6ZwmrSxZNnW-:b-10wiul) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L516)):*
> ```cpp
>         logger.insert("Path", FLAGS_db);
>         logger.insert("Engine", FLAGS_engine);
>         logger.insert( "Keys [bytes each]", FLAGS_key_size);
> ```

random extra whitespace (before `"Keys`)
___
*[bench/db_bench.cc, line 540 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOX9l29n1NRyUA1ZgV:-MNOX9l29n1NRyUA1ZgW:b-2vd26d) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L540)):*
> ```cpp
> #if defined(__linux)
>         time_t now = time(NULL);
>         logger.insert( "Date:", std::string(ctime(&now), 23));  // ctime() adds newline
> ```

I believe the comment in this line does not give us anymore value - you can remove it
___
*[bench/db_bench.cc, line 540 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOXJC96S6HN5kIo0Qc:-MNOXJC96S6HN5kIo0Qd:bpmtlib) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L540)):*
> ```cpp
> #if defined(__linux)
>         time_t now = time(NULL);
>         logger.insert( "Date:", std::string(ctime(&now), 23));  // ctime() adds newline
> ```

random extra whitespace - before `"Date` 
___
*[bench/db_bench.cc, line 760 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOXUoN6Jf7NajI9bMB:-MNOXUoN6Jf7NajI9bMC:b-y99l5b) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L760)):*
> ```cpp
>         auto thread_stats = arg[0].thread->stats;
>         logger.insert(name.ToString(), "micros/op" ,thread_stats.get_mic [...]

2020-12-02 07:36 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 2 of 14 files reviewed, 27 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOKG7h6rt3mBi1Pkxt:-MNXI-JNBE58VcQW39OF:bsvtryh) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Am I getting this correctly, you're installing in the same directory as the repository's path?
</blockquote></details>

yes. in temporary directory. 
___
*[run_benchmark.py, line 68 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOImK-BL0nKjrCC0GU:-MNXIEWb7ZoLwOTn8KSd:bm44vvn) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is an in-tree build? is it supported in our repos?
</blockquote></details>

Yes, it is in-tree build. It's partially supported, as there is no clean. However I don't see it is a problem, as it's all in temporary directory. Do you think it would be better to create separate installation and separate build directory?
___
*[run_benchmark.py, line 131 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOK_2IEp6IM0FqVWYP:-MNXKS0F5wCo-8jW-6Mu:b-ivz524) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L131)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`\n` - there's no `os.newline` or something to use?
</blockquote></details>

There is os.linesep, but it's tricky and usable only in very specific scenarios. 
___
*[bench/db_bench.cc, line 268 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUrJl8j4NxFadkdyi:-MNXLdIkBUqxAQqgUi6J:bifvjds) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L268)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

std::endl ?
</blockquote></details>

Nope. 
std::endl is "\n".  Definition of the CSV Format specifies that is should be "\r\n" https://tools.ietf.org/html/rfc4180


<!-- Sent from Reviewable.io -->

2020-12-02 15:14 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 2 of 14 files reviewed, 23 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOKG7h6rt3mBi1Pkxt:-MNZ-NYuCHa1iNTfRhfN:b-gs2t21) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

yes. in temporary directory. 
</blockquote></details>

agreed to add install dir
___
*[run_benchmark.py, line 68 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOImK-BL0nKjrCC0GU:-MNZ-Wbf7yQ0HUurxkaN:b-18zguq) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L68)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Yes, it is in-tree build. It's partially supported, as there is no clean. However I don't see it is a problem, as it's all in temporary directory. Do you think it would be better to create separate installation and separate build directory?
</blockquote></details>

agreed to drop it, since it works :)


<!-- Sent from Reviewable.io -->

2020-12-07 10:10 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 1 of 11 files reviewed, 22 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[Makefile, line 13 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MN8f0Gg2GmbxfE-lvwb:-MNh1-xF2KKTNVTVwO8r:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/Makefile#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line?
</blockquote></details>

Done.
___
*[run_benchmark.py, line 16 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MN8o9cU4AVVJJf2kln_:-MNh12It80WxcOtown-b:b-cg1dx7) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`exception` -> `ex` ?

side note - did you tested, this hook works?
</blockquote></details>

that's why we name it "draft" :) 
fixed, tested and works like a charm
___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOGjuk4BRb9PWr7iBD:-MNcSWnV7KJyG6Ohxlay:b9g3uub) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm afraid, if you specify an install path in the custom "cmake_params" it will be overwritten by your hard-coded prefix. I believe you can switch the sequence, firstly set your path then add "cmake_params"
</blockquote></details>

All those temporary directories mechanism wouldn't work if I stop overwriting this. 
___
*[run_benchmark.py, line 155 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNONfWYBv4rf3GjBsB2:-MNh5EHD9THW7Pp2h_t-:b-bb0ngx) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L155)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

required?
</blockquote></details>

'required' is invalid argument for positional arguments.
___
*[run_benchmark.py, line 195 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOOVnM1DgtIMByB1ro:-MNh4yvq7UUQ2l2ABGos:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L195)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

else: warning/info message
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 188 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOU2Jo5-TjNeFSxul-:-MNh5nGODn_UOPP9pHN1:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L188)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe, recently Igor found some guidelines, not to start var names with `_` - rename to `id_name_`/`id_name`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 233 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUbgH-PXBM9V9mSYi:-MNh5sge6bx4UEP2f8Js:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L233)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 237 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOUf_h9o0QQEvXkw87:-MNh61GS25YFVwfj0p7k:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L237)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`"\n"` -> `std::endl`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 516 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOVG_x6ZwmrSxZNnVz:-MNh8uN-5zrA_JxyDoxB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L516)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

random extra whitespace (before `"Keys`)
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 540 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOX9l29n1NRyUA1ZgV:-MNh9-a6E0nxRbZHrNxT:bpmnb8c) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L540)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe the comment in this line does not give us anymore value - you can remove it
</blockquote></details>

Done.
I don't like this line, but don't have idea how to remove this newline in some smooth way. 
___
*[bench/db_bench.cc, line 540 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOXJC96S6HN5kIo0Qc:-MNh9Njn-hb0EpFkQnUy:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L540)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

random extra whitespace - before `"Date` 
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 760 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOXUoN6Jf7NajI9bMB:-MNwfCu24B9N7G4691HI:b-sok87w) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L760)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

twice the same stat with different name?
</blockquote></details>

Copy-paste error. 
Done. 
___
*[bench/db_bench.cc, line 763 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOXaYw-MTOuivnQZat:-MNh9q2vBtFYjfR8ThSf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench/db_bench.cc#L763)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

extra whitespace within the line
</blockquote></details>

Done.
___
*[bench_scenarios/basic.json, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOPvpbDoD-zqaqy3sX:-MNhXZnNCnT-j60mygkU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/bench_scenarios/basic.json#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't these lines be aligned with the previous one (intended with the same spaces/tabs) 
</blockquote></details>

Done.
___
*[bench_scenarios/basic.json, line 15 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOQUMh-p5X9fij8_Z1:-MNh_0ZU0twP1stbJQJ9:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench_scenarios/basic.json#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can disable tests, examples and docs here too
</blockquote></details>

Done.
___
*[utils/jenkins/pmemkv-tools.jenkins, line 4 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOSp7G8w2UPl2CQclL:-MNwfNJc1zlO3YahL1u6:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/utils/jenkins/pmemkv-tools.jenkins#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update this line pls
</blockquote></details>

Done.
___
*[utils/jenkins/pmemkv-tools.jenkins, line 18 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOT2dI31PjTyWJ75FF:-MNwfTIg2wZyP2B3dj0c:b-896fix) ([raw file](https://gi [...]

2020-12-07 14:47 UTC, karczex commented
___
*[utils/jenkins/Jenkinsfile, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MMLMGqH7MCd4GF13X1-:-MNxeiID7Je5_xbRCC_3:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/utils/jenkins/Jenkinsfile#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update plox
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-08 14:18 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/37)* status: 4 of 11 files reviewed, 22 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOGjuk4BRb9PWr7iBD:-MO12h6p6EZUmVdLQWrO:buudfzc) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

All those temporary directories mechanism wouldn't work if I stop overwriting this. 
</blockquote></details>

I believe in some cases we may want to override it, e.g. used locally... anyway, maybe it's not a common usage, but, I guess, it doesn't hurt to switch the sequence (as I said, firstly set cmake_install_prefix and then set cmake_params)
___
*[run_benchmark.py, line 155 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNONfWYBv4rf3GjBsB2:-MO1IGOVEhVlCBImPisV:bgf3bfx) ([raw file](https://github.com/pmem/pmemkv-tools/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L155)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

'required' is invalid argument for positional arguments.
</blockquote></details>

true, mea culpa
___
*[run_benchmark.py, line 87 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1FDyh-QSvhb2OHwe6:-MO1FDyi2bHRnzuHkvwi:b-bzft32) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L87)):*
> ```Python
>                 check=True,
>             )
>             self.logger.debug(f"install dir: {os.listdir(self.install_path)}")
> ```

perhaps print somewhere what project you're building
___
*[run_benchmark.py, line 105 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1FcCQ5b3-bs8NmDsb:-MO1FcCQ5b3-bs8NmDsc:b-nsqcu9) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L105)):*
> ```Python
> 
>     def build(self):
> ```

redundant empty line
___
*[run_benchmark.py, line 120 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1FisX5AtdTbGR7vhw:-MO1FisX5AtdTbGR7vhx:b3kqx) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L120)):*
> ```Python
> 
>     def run(self):
> ```

.
___
*[run_benchmark.py, line 157 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1Gd0w1FM4d_b7krrc:-MO1Gd0w1FM4d_b7krrd:b-da0l9k) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L157)):*
> ```Python
>     with client:
>         db = client[db_name]
>         column = db["test_data"]
> ```

shouldn't this string also be a variable/param?
___
*[run_benchmark.py, line 171 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1H01eChdEj5vNkbnE:-MO1H01eChdEj5vNkbnF:b-d3s9sz) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L171)):*
> ```Python
> +-------------------------------------+       +-----------------------+
> |       run_benchmark.py              |       | libpmemobj-cpp        |
> |                                     |       | git repozitory        |
> ```

`z` -> `s`
___
*[run_benchmark.py, line 178 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1H1yL7v47Xa7og1wk:-MO1H1yL7v47Xa7og1wl:b3kqx) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L178)):*
> ```Python
> | | libpmemobj-cpp         |          |       +-----------------------+
> | | project                |          |       | pmemkv                |
> | +------------------------+          |       | git repozitory        |
> ```

.
___
*[run_benchmark.py, line 190 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1HM6E7oQ9dqUl4qAX:-MO1HM6E7oQ9dqUl4qAY:bou1ow0) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L190)):*
> ```Python
> |                                |    |       +-----------------------+
> | +------------------------+     |    |
> | | pmemkkv-bench          |     |    |
> ```

kkv? ;)
___
*[run_benchmark.py, line 217 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1Ip7PEp0xKzxPpYZw:-MO1Ip7PEp0xKzxPpYZx:b-svkd0r) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L217)):*
> ```Python
>     parser.add_argument("config_path", help="Path to json config file")
>     args = parser.parse_args()
>     logger.info(args.config_path)
> ```

wouldn't it be better if this will be formatted like this: `f"{args.config_path=}"` ?
___
*[bench/db_bench.cc, line 34 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1emxu3DfRnstcOBph:-MO1emxu3DfRnstcOBpi:b-ub9oa8) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L34)):*
> ```cpp
> #include "libpmemkv.hpp"
> 
> static const std::string USAGE =
> ```

update help, pls
___
*[bench/db_bench.cc, line 241 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1bwLc4BtIur2EIUrn:-MO1bwLc4BtIur2EIUro:b-mf3jbz) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L241)):*
> ```cpp
> private:
> 
> 	void combine_data()
> ```

pls add some comments in these logger classes
___
*[bench/db_bench.cc, line 256 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1agIS95LtRvXzDgQK:-MO1agIS95LtRvXzDgQL:b-r00c0e) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L256)):*
> ```cpp
> 	{
> 		combine_data();
> 		std::cout<< id_name;
> ```

why do we print this? and especially with no label/description
___
*[bench/db_bench.cc, line 980 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1_mAQ69UVkSqm2Nj8:-MO1_mAQ69UVkSqm2Nj9:b-o5hzhk) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L980)):*
> ```cpp
>     // Default engine name
>     static const char *FLAGS_engine = "cmap";
>     static int FLAGS_logger = 0;
> ```

pls add a comment, what's default logger
___
*[bench/db_bench.cc, line 1058 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1eVMQ9AbqoMYxWSZc:-MO1eVMQ9AbqoMYxWSZd:bgykan7) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L1058)):*
> ```cpp
>         std::remove(FLAGS_db);
>     }
>     logger->print();
> ```

what if there's no data to print? is it handled properly?
___
*[bench_scenarios/basic.json, line 15 at r4](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MNOQUMh-p5X9fij8_Z1:-MO1eqsE25ZHdrsieWpt:b-tm6av5) ([raw file](https://github.com/pmem/pmemkv-tools/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench_scenarios/basic.json#L15)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

examples=off ?
___
*[bench_scenarios/basic.json, line 32 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1hdqG1hYlo7D0uqqU:-MO1hdqG1hYlo7D0uqqV:b-7urw2o) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench_scenarios/basic.json#L32)):*
> ```JSON
>         "repo_url": "https://github.com/pmem/libpmemobj-cpp.git",
>         "commit": "HEAD",
>         "cmake_params": [
> ```

perhpas too "-DCMAKE_BUILD_TYPE=Release"
___
*[utils/jenkins/Jenkinsfile, line 4 at r6](https://reviewable.io/reviews/pmem/pmemkv-tools/37#-MO1eyBHAL2Nojqaj6-K:-MO1eyBHAL2Nojqaj6-L:b7lhbwb) ([raw file](https://github.com/pmem/pmemkv-tools/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/utils/jenkins/Jenkinsfile#L4)):*
> ```Groovy
> /* Copyright 2019-2020, Intel [...]

2020-12-09 09:55 UTC, igchor commented on run_benchmark.py
> +| | -----------------------+ <------------+   +-----------------------+
Wouldn't it be more readable to have those horizontal lines straight? ;d

2020-12-09 10:00 UTC, igchor commented on Makefile
> +bench: CFLAGS = $(shell pkg-config --cflags libpmemkv) -DOS_LINUX -fno-builtin-memcmp -march=native -DNDEBUG -O3 -std=c++11
Just increasing O2 to O3 is not always the best idea - the performance might be better on O2 for some cases. If you have some performance numbers to support this change that's fine but if not I'd prefer to leave it as was.

2020-12-09 10:28 UTC, igchor requested changes

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +    float get_throughput()
maybe some comment in what units the value is returned? (or include it in the function name?)

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +   Histogram get_histogram()
do you have to copy the histogram?

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +        logger.insert("Date:", std::string(ctime(&now), 23));
23?

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +    void print()
Does it even work without `virtual`?

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +    if(FLAGS_logger != CSV)
This is like double negation ;d Why not `if(FLAGS_logger) logger = new CsvLogger()`?

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +	void print_histogram()
Why this is implemented in the base class instead of in csv and human logger?

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +	std::map<std::string, std::map<std::string, std::string>> data_matrix;
any reason why this is map and not just a vector?

2020-12-09 10:28 UTC, igchor commented on bench/db_bench.cc
> +	std::map<std::string, std::string> global_data;
what is global_data and data_matrix and column_index anyway?

2020-12-09 11:03 UTC, igchor commented on bench/db_bench.cc
> +	void combine_data()
what is it for?

2020-12-14 11:55 UTC, igchor requested changes
> Reviewed 1 of 10 files at r6, 3 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 4 of 13 files reviewed, 31 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 980 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1_mAQ69UVkSqm2Nj8:-MOW5Nw2DMyDDTEvMLzr:b-v1n6z3) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L980)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a comment, what's default logger
</blockquote></details>

is there even possibility to change it right now?
___
*[bench/db_bench.cc, line 327 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW1ZWx3bm15QhSIFxS:-MOW1ZWx3bm15QhSIFxT:bxlvw3i) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L327)):*
> ```cpp
>     }
> 
>    Histogram get_histogram()
> ```

why by copy?
___
*[bench/db_bench.cc, line 519 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW3aaBDx7d1Aa9tM03:-MOW3aaBDx7d1Aa9tM04:b-d5z9y0) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L519)):*
> ```cpp
>             method = &Benchmark::ReadRandomWriteRandom;
>         } else {
>             // XXX: Throw exception
> ```

so do it ;d
___
*[bench/db_bench.cc, line 531 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW3F6MBH8IJTKs0exf:-MOW3F6N7AXPEXKsnfZw:b-55j6m5) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L531)):*
> ```cpp
>     ~Benchmark()
>     {
>         kv_->close();
> ```

why? that's a memory leak, btw, it would be better to use std::unique_ptr here
___
*[bench/db_bench.cc, line 936 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW5S181Fw5gRNAQE_6:-MOW5S181Fw5gRNAQE_7:b-1edlzw) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L936)):*
> ```cpp
>     g_env = leveldb::Env::Default();
> 
>     BenchmarkLogger *logger = new BenchmarkLogger;
> ```

If you have to use dynamic allocation (I think you don't) then please use something like unique_ptr
___
*[bench/db_bench.cc, line 938 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW5d-94tGLhitywgUd:-MOW5d-94tGLhitywgUe:b2znkdg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L938)):*
> ```cpp
>     BenchmarkLogger *logger = new BenchmarkLogger;
> 
>     pmem::kv::db *kv = NULL;
> ```

what is this for, isn't there kv in the benchmark class?
___
*[bench/db_bench.cc, line 954 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW5ajb7eUm31EU89E_:-MOW5ajb7eUm31EU89Ea:bdfunri) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L954)):*
> ```cpp
>             benchmark.Run();
>     }
>     if (kv !=NULL) {
> ```

Wasnt' this moved to benchmark implementation
___
*[bench/util/csv.h, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2Ytr27NAw1NoYOiP:-MOW2Ytr27NAw1NoYOiQ:b-kdi8dp) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L1)):*
> ```objc
> #pragma once
> ```

licence?
___
*[bench/util/csv.h, line 12 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2HlG6Cm2F3vgHEG0:-MOW2HlHCbDcR9DkF_I1:b5s8lsl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L12)):*
> ```objc
> private:
> 
> 	std::map<std::string, std::map<std::string, std::string>> data_matrix;
> ```

can you explain what it is? or change the name to something more meanigful?
___
*[bench/util/csv.h, line 44 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2Pj1E7Bw0qkGNBVB:-MOW2Pj1E7Bw0qkGNBVC:be244ep) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L44)):*
> ```objc
> 			std::cout << "," << column;
> 		}
> 		std::cout << "\r\n";
> ```

don't use "\r\n" or even "\n" - this might not flush the data at all, instead use std::endl; (fix in all places)


<!-- Sent from Reviewable.io -->

2020-12-14 13:11 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 31 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[run_benchmark.py, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MNOGjuk4BRb9PWr7iBD:-MOWFZFx6V3_h_2EuhC2:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/cbe18834c3ee37f8cf111543732a4d6d0ca13621/run_benchmark.py#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe in some cases we may want to override it, e.g. used locally... anyway, maybe it's not a common usage, but, I guess, it doesn't hurt to switch the sequence (as I said, firstly set cmake_install_prefix and then set cmake_params)
</blockquote></details>

Done.
___
*[run_benchmark.py, line 87 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1FDyh-QSvhb2OHwe6:-MOH9jRf5Qxls9O6RCZP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps print somewhere what project you're building
</blockquote></details>

Done.
___
*[run_benchmark.py, line 105 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1FcCQ5b3-bs8NmDsb:-MOHAuOT8HUWnmYRCIDs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L105)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[run_benchmark.py, line 120 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1FisX5AtdTbGR7vhw:-MO2-Y1P4nEIeLaxofzU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L120)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[run_benchmark.py, line 157 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1Gd0w1FM4d_b7krrc:-MOHBZ6O0Mo4mx-wRnem:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L157)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't this string also be a variable/param?
</blockquote></details>

Done.
___
*[run_benchmark.py, line 171 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1H01eChdEj5vNkbnE:-MO2-fBu3ZCXWC_8OFbW:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L171)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`z` -> `s`
</blockquote></details>

Done.
___
*[run_benchmark.py, line 174 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MML5u5jXDShQ68WQBhn-r6-174:-MOHBfAL7elDTiP88GfL:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L174)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Wouldn't it be more readable to have those horizontal lines straight? ;d
</blockquote></details>

Done.
___
*[run_benchmark.py, line 178 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1H1yL7v47Xa7og1wk:-MO2-fUL3IvccSLBWArW:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L178)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[run_benchmark.py, line 190 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1HM6E7oQ9dqUl4qAX:-MO2-mWL9LTtOkRKaOx8:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L190)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

kkv? ;)
</blockquote></details>

Done.
___
*[run_benchmark.py, line 217 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1Ip7PEp0xKzxPpYZw:-MO2-sfRAfrIfXOm3_2C:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/run_benchmark.py#L217)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

wouldn't it be better if this will be formatted like this: `f"{args.config_path=}"` ?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 34 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1emxu3DfRnstcOBph:-MOHCDDjDN_Ynyi5IlXQ:b4itaod) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update help, pls
</blockquote></details>

csv flag was removed, so udpdate is not needed. 
___
*[bench/db_bench.cc, line 980 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1_mAQ69UVkSqm2Nj8:-MOHCTJs5UW4w3tN2ULU:brpmqc3) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L980)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a comment, what's default logger
</blockquote></details>

removed.
___
*[bench/db_bench.cc, line 1058 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1eVMQ9AbqoMYxWSZc:-MOHCUwD1rIIQUPuZic5:b-7g7nkc) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L1058)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what if there's no data to print? is it handled properly?
</blockquote></details>

yes. 
___
*[bench/db_bench.cc, line 936 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW5S181Fw5gRNAQE_6:-MOWGcKH6aL5Y-Ikla6v:blx8kdb) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L936)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If you have to use dynamic allocation (I think you don't) then please use something like unique_ptr
</blockquote></details>

Dynamic allocation is not needed any more. 
Done.
___
*[bench/util/csv.h, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2Ytr27NAw1NoYOiP:-MOWMDQC5C7I2ntIX9FZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

licence?
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 44 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2Pj1E7Bw0qkGNBVB:-MOWH4BeCm0rAIjoJu0A:b-cu9703) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

don't use "\r\n" or even "\n" - this might not flush the data at all, instead use std::endl; (fix in all places)
</blockquote></details>

in csv format line should end with "\r\n". std::endl on the other hand adds only "\n"

rfc: https://tools.ietf.org/html/rfc4180#page-2
___
*[bench_scenarios/basic.json, line 15 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MNOQUMh-p5X9fij8_Z1:-MOHDJlBChDdoDnUVnYY:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/bench_scenarios/basic.json#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><block [...]

2020-12-14 13:42 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 31 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 955 at r9](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOWUA8d5uMXd1q5tp_z:-MOWUA8d5uMXd1q5tpa-:bdltysr) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c82e95a95af3f36b55544415e5671d5f4f9ec5d6/bench/db_bench.cc#L955)):*
> ```cpp
>     if (kv !=NULL) {
>         delete kv;
>         std::remove(FLAGS_db);
> ```

please remove this line


<!-- Sent from Reviewable.io -->

2020-12-14 13:55 UTC, karczex commented
___
*[bench/db_bench.cc, line 531 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW3F6MBH8IJTKs0exf:-MOWX9Iq1wRBuSl_v5z4:b-2nrq9l) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L531)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why? that's a memory leak, btw, it would be better to use std::unique_ptr here
</blockquote></details>

As we discussed off-line, kv object is managed by main


<!-- Sent from Reviewable.io -->

2020-12-14 13:57 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 31 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 938 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW5d-94tGLhitywgUd:-MOWXOSFEL8bT0E0Lk9K:bskc4qd) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L938)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is this for, isn't there kv in the benchmark class?
</blockquote></details>

No. kv object is intended to be shared between Benchmark objects.
___
*[bench/db_bench.cc, line 954 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW5ajb7eUm31EU89E_:-MOWXa4F-uzvRli-9b_o:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L954)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Wasnt' this moved to benchmark implementation
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2020-12-14 14:39 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 27 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/util/csv.h, line 44 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2Pj1E7Bw0qkGNBVB:-MOWg4RWAL-oCJq9QwWD:b-s2zs4) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L44)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

in csv format line should end with "\r\n". std::endl on the other hand adds only "\n"

rfc: https://tools.ietf.org/html/rfc4180#page-2
</blockquote></details>

Hm, ok, so in that case at leas add one std::endl (or some equivalent flush?) at the end to ensure output is really printed.


<!-- Sent from Reviewable.io -->

2020-12-14 15:15 UTC, karczex commented
___
*[bench/util/csv.h, line 12 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2HlG6Cm2F3vgHEG0:-MOWoBQ9BRn9GbMnEihr:bqm1v8i) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

can you explain what it is? or change the name to something more meanigful?
</blockquote></details>

do you have any idea for better name? 
"table", "spreadsheet"? 


<!-- Sent from Reviewable.io -->

2020-12-14 15:18 UTC, karczex commented
___
*[bench/db_bench.cc, line 519 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW3aaBDx7d1Aa9tM03:-MOWpDHO9yvhhwuwn7Mf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L519)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

so do it ;d
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 15:19 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 27 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 980 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1_mAQ69UVkSqm2Nj8:-MOWpGPeA2OMjLZQ6X-W:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L980)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

removed.
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 955 at r9](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOWUA8d5uMXd1q5tp_z:-MOWpHPOCi4Qwn2s7aJ9:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c82e95a95af3f36b55544415e5671d5f4f9ec5d6/bench/db_bench.cc#L955)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please remove this line
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 44 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2Pj1E7Bw0qkGNBVB:-MOWpMcV1VFnE-wbmlzw:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, ok, so in that case at leas add one std::endl (or some equivalent flush?) at the end to ensure output is really printed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 15:29 UTC, karczex commented
___
*[utils/jenkins/Jenkinsfile, line 4 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1eyBHAL2Nojqaj6-K:-MOWpaie3qazM4fdtF4y:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/utils/jenkins/Jenkinsfile#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`initial jenkins job`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 15:49 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 27 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[utils/jenkins/Jenkinsfile, line 174 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1fdYC1VY1OY8CGm-W:-MOWvwcWE0Ktavsho8mi:bfw3430) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/utils/jenkins/Jenkinsfile#L174)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope
</blockquote></details>

I removed pmemkv-bench_matrix job, as it seems to be redundant for this repo.
___
*[utils/jenkins/Jenkinsfile, line 182 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1ffUW9v21cVUh3Srg:-MOWw1iP3_2HNipOuz_o:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/utils/jenkins/Jenkinsfile#L182)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`${TEST_TYPE}` ?
</blockquote></details>

.
___
*[utils/jenkins/pmemkv-tools.jenkins, line 9 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MNOTIoW0a0iWS9RIX9P:-MOWwADn8yUCaFH21giD:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/fcfc7767d50114a5a7a0e7893097c9493e436d9c/utils/jenkins/pmemkv-tools.jenkins#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this should be updated for this repository
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 16:21 UTC, karczex commented
___
*[bench/db_bench.cc, line 256 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1agIS95LtRvXzDgQK:-MOWwVq44rs4K22mXm7g:bkeql7c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L256)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we print this? and especially with no label/description
</blockquote></details>

there was label all the time. I change this little bit. I hope it's more readable now. 


<!-- Sent from Reviewable.io -->

2020-12-14 16:35 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 27 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 327 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW1ZWx3bm15QhSIFxS:-MOX5ZRNB6jNXezNiW7p:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/db_bench.cc#L327)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why by copy?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-14 16:49 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 3 of 13 files reviewed, 26 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/util/csv.h, line 12 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2HlG6Cm2F3vgHEG0:-MOX8LnT3CkEqt8J4FC0:b-ybyeft) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L12)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

do you have any idea for better name? 
"table", "spreadsheet"? 
</blockquote></details>

The name is maybe not so bad, but some comment would be nice - how the data is stored - key represent row etc.
___
*[bench/util/csv.h, line 16 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOX8m3l7qxzV2RuIivT:-MOX8m3l7qxzV2RuIivU:b-j9q795) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/csv.h#L16)):*
> ```objc
> private:
> 
> 	std::map<std::string, std::map<std::string, std::string>> data_matrix;
> ```

Why is this std::map and not just std::vector<std::vector<std::string>>`?
___
*[bench/util/csv.h, line 17 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOX8YKbEpoliWSUGtex:-MOX8YKbEpoliWSUGtey:b-q0tzys) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/csv.h#L17)):*
> ```objc
> 
> 	std::map<std::string, std::map<std::string, std::string>> data_matrix;
> 	std::set<std::string> column_index;
> ```

what is it for?
___
*[bench/util/csv.h, line 18 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOX8_qU9p7AoFVXN33z:-MOX8_qU9p7AoFVXN34-:bqlq7vl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/csv.h#L18)):*
> ```objc
> 	std::map<std::string, std::map<std::string, std::string>> data_matrix;
> 	std::set<std::string> column_index;
> 	std::string id_name;
> ```

what is id_name? is it benchmark name?


<!-- Sent from Reviewable.io -->

2020-12-14 20:53 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 14 files at r3, 2 of 10 files at r6, 3 of 9 files at r7, 2 of 4 files at r8, 1 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 11 of 13 files reviewed, 14 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 189 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXqjn73edil-3NAp-D:-MOXqjn73edil-3NAp-E:bcms80s) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/run_benchmark.py#L189)):*
> ```Python
> | | +----------------------+ <----------------+                       |
> | | Downloads and builds   |          |       |                       |
> | | pmemk^ project         |          |       +-----------------------+
> ```

pmemk^ ?
___
*[run_benchmark.py, line 193 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXqbEP3tgzVC0OQz5M:-MOXqbEP3tgzVC0OQz5N:b-70ej1a) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/run_benchmark.py#L193)):*
> ```Python
> |                                     |
> |                                     |       +-----------------------+
> | +------------------------+          |       | pmemkv+tools          |
> ```

repo name has changed
___
*[run_benchmark.py, line 229 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXrBj9DoVDfyqrC8Ma:-MOXrBj9DoVDfyqrC8Mb:bgcn02o) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/run_benchmark.py#L229)):*
> ```Python
> 
>     # Setup database
>     db_address = db_port = db_user = db_passwd = db_name = None
> ```

db_collection = none, too?
___
*[bench/db_bench.cc, line 256 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1agIS95LtRvXzDgQK:-MOXu0Ga4NtJkECO-wz0:bogsb27) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/bench/db_bench.cc#L256)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

there was label all the time. I change this little bit. I hope it's more readable now. 
</blockquote></details>

yes, thanks
___
*[bench/db_bench.cc, line 10 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXupWm10YjjVhh-z6Z:-MOXupWm10YjjVhh-z6_:b3x9tgu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/db_bench.cc#L10)):*
> ```cpp
> 
> // Copyright (c) 2017-2020, Intel Corporation
> // This source code is licensed under the Apache 2.0 License
> ```

SPDX identifier...? maybe make all licenses similar in all files (at least the one you touched here; the rest may be updated in sep. PR)
___
*[bench/db_bench.cc, line 23 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXuQKe-f4OfZBUqcZ3:-MOXuQKe-f4OfZBUqcZ4:b-qlknf2) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/db_bench.cc#L23)):*
> ```cpp
> #include <iostream>
> #include <iomanip>
> #include <map>
> ```

do you need map here?
___
*[bench/db_bench.cc, line 524 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXtkspAOkEC4lJj3xy:-MOXtkspAOkEC4lJj3xz:bnqc4du) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/db_bench.cc#L524)):*
> ```cpp
>             method = &Benchmark::ReadRandomWriteRandom;
>         } else {
>             throw std::runtime_error("unknown benchmark " + name.ToString());
> ```

perhaps make it `benchmark: ` or put name in `'name'` (like it was before)
___
*[bench/util/histogram.h, line 4 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXulUS7GIBzwN0JLJc:-MOXulUS7GIBzwN0JLJd:b-kdhwil) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/histogram.h#L4)):*
> ```objc
> // Use of this source code is governed by a BSD-style license that can be
> // found in the LICENSE-BSD file. See the AUTHORS file for names of contributors.
> ```

license?
___
*[utils/jenkins/Jenkinsfile, line 4 at r6](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MO1eyBHAL2Nojqaj6-K:-MOY0m5HDsckd3QHKT9D:bfczthc) ([raw file](https://github.com/pmem/pmemkv-bench/blob/8a8532dad08273ce4eec970bcce90a153325e2cc/utils/jenkins/Jenkinsfile#L4)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

matrix is removed now, pls update
___
*[utils/jenkins/Jenkinsfile, line 65 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOY0oZMAQiZKJI-KDJF:-MOY0oZMAQiZKJI-KDJG:b-cbkmak) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/utils/jenkins/Jenkinsfile#L65)):*
> ```Groovy
> '''
> 
> coverage_param = '''
> ```

and coverage not needed here
___
*[utils/jenkins/pmemkv-bench.jenkins, line 92 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOY0dD72JXkAvGU_aUG:-MOY0dD72JXkAvGU_aUH:b-l56kjm) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/utils/jenkins/pmemkv-bench.jenkins#L92)):*
> ```
> 						def COV_PARAM=""
> 						def TEST_DIR
> 						if (params.COVERAGE == 'yes') {
> ```

then remove coverage here too


<!-- Sent from Reviewable.io -->

2020-12-15 10:40 UTC, karczex commented
___
*[bench/util/csv.h, line 18 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOX8_qU9p7AoFVXN33z:-MO_ye99-ZmKFtuSMPBY:b-hfpwum) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/csv.h#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is id_name? is it benchmark name?
</blockquote></details>

it's generic csv library, with first column name defined in constructor typically is some kind of identifier.


<!-- Sent from Reviewable.io -->

2020-12-15 12:40 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 5 of 13 files reviewed, 14 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[run_benchmark.py, line 189 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXqjn73edil-3NAp-D:-MOaMfUn8HE7mIgVlUNs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/run_benchmark.py#L189)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pmemk^ ?
</blockquote></details>

Done.
___
*[run_benchmark.py, line 193 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXqbEP3tgzVC0OQz5M:-MOaPXvg5EgP5IGitd3v:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/run_benchmark.py#L193)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

repo name has changed
</blockquote></details>

Done.
___
*[run_benchmark.py, line 229 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXrBj9DoVDfyqrC8Ma:-MOaPYl_9IpOQNmVDErB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/run_benchmark.py#L229)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

db_collection = none, too?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 10 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXupWm10YjjVhh-z6Z:-MOaP_C58ZzWPRuEpJ7O:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/db_bench.cc#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

SPDX identifier...? maybe make all licenses similar in all files (at least the one you touched here; the rest may be updated in sep. PR)
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 23 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXuQKe-f4OfZBUqcZ3:-MOaPaCTBWVwUWyqAL1Y:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/db_bench.cc#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you need map here?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 524 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXtkspAOkEC4lJj3xy:-MOaPbAfDITC8mlrVsxM:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/db_bench.cc#L524)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make it `benchmark: ` or put name in `'name'` (like it was before)
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 12 at r7](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOW2HlG6Cm2F3vgHEG0:-MOaMQG98evMvIfKVXcq:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/3c043b68f434e189842c4bd40f00857f5d4e88ee/bench/util/csv.h#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The name is maybe not so bad, but some comment would be nice - how the data is stored - key represent row etc.
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 16 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOX8m3l7qxzV2RuIivT:-MOaH3vg3E5F_meEVtuo:b-c7ista) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/csv.h#L16)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why is this std::map and not just std::vector<std::vector<std::string>>`?
</blockquote></details>

for access to data in such manner:
```
data_matrix[row][column] = data;
```
___
*[bench/util/csv.h, line 17 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOX8YKbEpoliWSUGtex:-MOaJ2ux5Jq-MMLSkOoL:b-faqw5m) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/csv.h#L17)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is it for?
</blockquote></details>

it's a set of all columns
___
*[bench/util/histogram.h, line 4 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOXulUS7GIBzwN0JLJc:-MOaPgnM7igYBwXF19Na:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/bench/util/histogram.h#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

license?
</blockquote></details>

Done.
___
*[utils/jenkins/Jenkinsfile, line 65 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOY0oZMAQiZKJI-KDJF:-MOaMb8qCwA4JU6XjUb5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/utils/jenkins/Jenkinsfile#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and coverage not needed here
</blockquote></details>

Done.
___
*[utils/jenkins/pmemkv-bench.jenkins, line 92 at r11](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOY0dD72JXkAvGU_aUG:-MOaMd3f1oFI5ELX4cS-:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/ede4a4069e8d7fe01c9bb87369f36989f8e36ec9/utils/jenkins/pmemkv-bench.jenkins#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

then remove coverage here too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-15 13:27 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-:-MOa_LWG-TVioj_Oqm5m:bnfp4nl)* status: 5 of 13 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-12-15 13:31 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 5 of 13 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 672 at r12](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOaa8Ga68oA9mbTcU6m:-MOaa8Ga68oA9mbTcU6n:bqoq5a6) ([raw file](https://github.com/pmem/pmemkv-bench/blob/39734b9606aab6478bbaf5434e0e25479a85d4fe/bench/db_bench.cc#L672)):*
> ```cpp
> 				auto start = g_env->NowMicros();
> 				std::remove(FLAGS_db);
> 				logger.insert(name, "[millis millis/op]", ((g_env->NowMicros() - start) * 1e-3));
> ```

Shouldn'y this be `Remove [millis/op]`?


<!-- Sent from Reviewable.io -->

2020-12-15 13:56 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 5 of 13 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 672 at r12](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOaa8Ga68oA9mbTcU6m:-MOafyzGCM4quDbdn7lP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/39734b9606aab6478bbaf5434e0e25479a85d4fe/bench/db_bench.cc#L672)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Shouldn'y this be `Remove [millis/op]`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-15 18:11 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 9 files at r7, 6 of 7 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @karczex)

___
*[bench/util/csv.h, line 15 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObXoudENaKnezkZJwp:-MObXoudENaKnezkZJwq:b3bpw8b) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L15)):*
> ```objc
> {
> private:
> 	/* Hold data in two dimensional map of strings: data_matrix[row][column]
> ```

`two-dimensional` I guess
___
*[bench/util/csv.h, line 18 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObY1fpAt8N6haWs7Ed:-MObY1fpAt8N6haWs7Ee:bpy9cgz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L18)):*
> ```objc
> 	 */
> 	std::map<std::string, std::map<std::string, std::string>> data_matrix;
> 	/* List of all columns, which is filled during inserts. Needed to
> ```

needed **for**
___
*[bench/util/csv.h, line 19 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObZ0io6hP0hJLzvCSb:-MObZ0io6hP0hJLzvCSc:bmw945o) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L19)):*
> ```objc
> 	std::map<std::string, std::map<std::string, std::string>> data_matrix;
> 	/* List of all columns, which is filled during inserts. Needed to
> 	 * printing header  and data in the same order.
> ```

double space before `  and`
___
*[bench/util/csv.h, line 25 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObXaZr5ZM1e7eiQCgg:-MObXaZs2ozTuBmtpBAT:b6cfywn) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L25)):*
> ```objc
> 
> public:
> 	CSV(std::string id_collumn_name) : id_name(id_collumn_name){};
> ```

`column` (misspell x2)
___
*[bench/util/csv.h, line 66 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOb_T1D0LC8Xoq7UAiy:-MOb_T1D0LC8Xoq7UAiz:b-rfki7g) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L66)):*
> ```objc
> };
> ```

redundant empty lines
___
*[bench_scenarios/local.json, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MMLKmNACQXUsRmPRKPZ:-MObaMOtAGyiSiLuOObV:bs0b4c7) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/bench_scenarios/local.json#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

och, too bad. Perhaps then, some extra readme file with short descriptions...?
</blockquote></details>

what about this?


<!-- Sent from Reviewable.io -->

2020-12-16 09:35 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2020-12-16 14:33 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37)* status: 12 of 14 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[bench/util/csv.h, line 15 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObXoudENaKnezkZJwp:-MOfy1Er3P3KvA98LlsP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`two-dimensional` I guess
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 18 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObY1fpAt8N6haWs7Ed:-MOfy1pY6XgDB1W-TfB5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

needed **for**
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 19 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObZ0io6hP0hJLzvCSb:-MOfy2q492iU1mvzMjSi:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

double space before `  and`
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 25 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MObXaZr5ZM1e7eiQCgg:-MOfy4lXDU7yl52hIGM-:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`column` (misspell x2)
</blockquote></details>

Done.
___
*[bench/util/csv.h, line 66 at r13](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MOb_T1D0LC8Xoq7UAiy:-MOfy5VM6E8SvK_ne3HS:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/867b8dca3f5973f1fac7ecfb6e4f93932cff2dfd/bench/util/csv.h#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty lines
</blockquote></details>

Done.
___
*[bench_scenarios/local.json, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-MMLKmNACQXUsRmPRKPZ:-MOfy6wB7Ojwn5bjviNJ:b-hgkkka) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e0fc82548031b73c6569a83a018fdb5a7fd8f408/bench_scenarios/local.json#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about this?
</blockquote></details>

Added json schema. 


<!-- Sent from Reviewable.io -->

2020-12-16 15:11 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/37#-:-MOg5jz6Eg7o3aowtYkc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2020-12-16 15:12 UTC, merged