Change date format in pmemkv-bench
RobDickinson/pmemkv-tools pull request #61
Opened 2021-02-19 14:12 UTC by karczex

This change simplify automatic parsing of date in 3rd party software.
I tested this time format with mongoDB charts and LibreOffice Calc.

2021-02-22 08:42 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[bench/db_bench.cc, line 511 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU7tVVw0T2Y6--4Myc4:-MU7tVVw0T2Y6--4Myc5:b-nn869j) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L511)):*
> ```cpp
> 		constexpr int time_string_size = 18;
> 		char formatted_time[time_string_size];
> 		std::strftime(formatted_time, time_string_size, "%D %T ", localtime(&now));
> ```

the space after `%T` is on purpose?


<!-- Sent from Reviewable.io -->

2021-02-22 12:09 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[bench/db_bench.cc, line 509 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU8c_FADxB05UQ_ugLl:-MU8c_FADxB05UQ_ugLm:bsrcwbs) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L509)):*
> ```cpp
> #if defined(__linux)
> 		auto now = std::time(NULL);
> 		constexpr int time_string_size = 18;
> ```

why 18? maybe replace it with something like strlen("date_format_you_wish_to_have");? e.g. strlen ("01/01/2021 11:11") + 1?
___
*[bench/db_bench.cc, line 511 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU8csis8acUMf6ZVB7t:-MU8csis8acUMf6ZVB7u:b-4fyp9d) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L511)):*
> ```cpp
> 		constexpr int time_string_size = 18;
> 		char formatted_time[time_string_size];
> 		std::strftime(formatted_time, time_string_size, "%D %T ", localtime(&now));
> ```

maybe check for any errors from strtfitime (if return value is != 0)


<!-- Sent from Reviewable.io -->

2021-02-22 22:49 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 20 unresolved discussions (waiting on @karczex)

___
*[bench/db_bench.cc, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU9YPxcEXidve0pTy90:-MU9YPxdC0jr8OFEyaY5:b-x6i67c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L16)):*
> ```cpp
> #include <cstdlib>
> #include <ctime>
> #include <inttypes.h>
> ```

C++ header: <cinttypes>
___
*[bench/db_bench.cc, line 73 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAdXja9cnr9KzUQ4U7:-MUAdXja9cnr9KzUQ4U8:bjxuou9) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L73)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
> // Number of key/values to place in database
> static int FLAGS_num = 1000000;
> static bool FLAGS_disjoint = false;
> // Number of read operations to do.  If negative, do FLAGS_num reads.
> static int FLAGS_reads = -1;
> // Number of concurrent threads to run.
> static int FLAGS_threads = 1;
> static int FLAGS_key_size = 16;
> // Size of each value
> static int FLAGS_value_size = 100;
> // Print histogram of operation timings
> static bool FLAGS_histogram = false;
> // Use the db with the following name.
> static const char *FLAGS_db = "/dev/shm/pmemkv";
> // Use following size when opening the database.
> static int FLAGS_db_size_in_gb = 0;
> static const double FLAGS_compression_ratio = 1.0;
> static const int FLAGS_ops_between_duration_checks = 1000;
> static const int FLAGS_duration = 0;
> static int FLAGS_readwritepercent = 90;
> static int FLAGS_tx_size = 10;
> ```
</details>


Maybe group this in structure. 
___
*[bench/db_bench.cc, line 195 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAnlT-EsVxOd-PG2bk:-MUAnlT-EsVxOd-PG2bl:b-bsfe4m) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L195)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> private:
> 	struct hist {
> 		int id;
> 		std::string name;
> 		std::string histogram;
> 	};
> 	int id = 0;
> 	std::vector<hist> histograms;
> 	CSV<int> csv = CSV<int>("id");
> ```
</details>

private section should be on the bottom
___
*[bench/db_bench.cc, line 240 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAqlWnBONBhXsBqPfT:-MUAqlWnBONBhXsBqPfU:b-fy0668) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L240)):*
> ```cpp
> 
> class Stats {
> private:
> ```

move to end
___
*[bench/db_bench.cc, line 337 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAqwczDiMnGUcZojFF:-MUAqwczDiMnGUcZojFG:bb7e8br) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L337)):*
> ```cpp
> 			else
> 				next_report_ += 100000;
> 			fprintf(stderr, "... finished %d ops%30s\r", done_, "");
> ```

cerr
___
*[bench/db_bench.cc, line 394 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUArJuL75vAKyCx8-kx:-MUArJuL75vAKyCx8-ky:bpka10r) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L394)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	// Each thread goes through the following states:
> 	//    (1) initializing
> 	//    (2) waiting for others to be initialized
> 	//    (3) running
> 	//    (4) done
> ```
</details>

Sounds like deterministic finite automata
___
*[bench/db_bench.cc, line 420 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUArcrR1QOrv99JkRGA:-MUArcrR1QOrv99JkRGB:b495523) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L420)):*
> ```cpp
> 
> class Duration {
> 	typedef std::chrono::high_resolution_clock::time_point time_point;
> ```

This is private by default, so should be moved to proper section
___
*[bench/db_bench.cc, line 468 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAd35M09y19zCX67w-:-MUAd35N14FvB7AYudH0:b-s53crz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L468)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	pmem::kv::db *kv_;
> 	int num_;
> 	int tx_size_;
> 	int value_size_;
> 	int key_size_;
> 	int reads_;
> 	int64_t readwrites_;
> ```
</details>

Please remove all '_'
___
*[bench/db_bench.cc, line 477 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAutBdB7oOd5OkHBY5:-MUAutBdB7oOd5OkHBY6:bc0t86d) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L477)):*
> ```cpp
> 	BenchmarkLogger &logger;
> 	Slice name;
> 	int n;
> ```

'n' tells nothing about variable
___
*[bench/db_bench.cc, line 486 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAcuSj-IS1axNvmLS7:-MUAcuSj-IS1axNvmLS8:b-6dhg1s) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L486)):*
> ```cpp
> 		PrintEnvironment();
> 		logger.insert("Path", FLAGS_db);
> 		logger.insert("Engine", engine);
> ```

FLAGS_engine?
___
*[bench/db_bench.cc, line 489 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAcwua943Oe0XIL7vI:-MUAcwua943Oe0XIL7vJ:b-ya81ng) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L489)):*
> ```cpp
> 		logger.insert("Keys [bytes each]", FLAGS_key_size);
> 		logger.insert("Values [bytes each]", FLAGS_value_size);
> 		logger.insert("Entries", num_);
> ```

Same as above
___
*[bench/db_bench.cc, line 508 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU9YlAi2GlW0hNhpy0D:-MU9YlAi2GlW0hNhpy0E:b-1f5a3w) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L508)):*
> ```cpp
> 	{
> #if defined(__linux)
> 		auto now = std::time(NULL);
> ```

nullptr instead of NULL
___
*[bench/db_bench.cc, line 537 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAUtx_12xiX10mHYtW:-MUAUtx_12xiX10mHYtX:b-g5s8wp) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L537)):*
<details><summary><i alt="summary">Quoted 25 lines of code…</i></summary>

> ```
> 		FILE *cpuinfo = fopen("/proc/cpuinfo", "r");
> 		if (cpuinfo != NULL) {
> 			char line[1000];
> 			int num_cpus = 0;
> 			std::string cpu_type;
> 			std::string cache_size;
> 			while (fgets(line, sizeof(line), cpuinfo) != NULL) {
> 				const char *sep = strchr(line, ':');
> 				if (sep == NULL) {
> 					continue;
> 				}
> 				Slice key = TrimSpace(Slice(line, sep - 1 - line));
> 				Slice val = TrimSpace(Slice(sep + 1));
> 				if (key == "model name") {
> 					++num_cpus;
> 					cpu_type = val.ToString();
> 				} else if (key == "cache size") {
> 					cache_size = val.ToString();
> 				}
> 			}
> 			fclose(cpuinfo);
> 			logger.insert("CPU", std::to_string(num_cpus));
> 			logger.insert("CPU model", cpu_type);
> 			logger.insert("CPUCache", cache_size);
> 		}
> ```
</details>


I'd prefer C++ style in C++ files:
```c++
    string single_line;
    string seek_phrase = "processor";
    ifstream file;
    int cpu_num = 0;
    file.open("/proc/cpuinfo");

    while (file.good()) {
        getline(file, single_line);
        if (!single_line.compare(0, cpu_phrase.length(), cpu_phrase)) {
            core_counter++;
        }
        if (!single_line.compare(0, cache_phrase.length(), cache_phrase)) {
            cache_size = single_line.substr(single_line.find_first_of("0123456789"));
        }
    }
    file.close();
    cout << cpu_num << endl;
```
___
*[bench/db_bench.cc, line 544 at r1](https://reviewable.io/re [...]

2021-02-23 14:20 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: 0 of 1 files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 511 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU7tVVw0T2Y6--4Myc4:-MUEFd3k0pajXu-ccBj1:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L511)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the space after `%T` is on purpose?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 511 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU8csis8acUMf6ZVB7t:-MUEFdrK2uM4CPTloCmC:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L511)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe check for any errors from strtfitime (if return value is != 0)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 15:07 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU9YPxcEXidve0pTy90:-MUEQN978fqpFiUH0dhs:blx2kko) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L16)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

C++ header: <cinttypes>
</blockquote></details>

<cinttypes>


<!-- Sent from Reviewable.io -->

2021-02-23 15:08 UTC, KFilipek reviewed
We agreed that the rest of comments will be resolved as separate issue, which is also created. 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-:-MUEQcH00HuC8lfAL4VU:b-pg91nb)* status: all files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-02-23 15:14 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor and @karczex)

___
*[bench/db_bench.cc, line 511 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU8csis8acUMf6ZVB7t:-MUERxau8sP9m_w0t9TN:bgsjwxj) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L511)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't we need the date for mongoCharts? shouldn't we break if this parsing fails?


<!-- Sent from Reviewable.io -->

2021-02-24 08:36 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[bench/db_bench.cc, line 545 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAuF_RBQPTk1ZbgS3O:-MUIAJN64cnBRQ_ZqExO:b-8xjp63) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L545)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

reads_(FLAGS_reads < 0 ? FLAGS_num : FLAGS_reads)
readwrites_(FLAGS_reads < 0 ? FLAGS_num : FLAGS_reads)
so, what's the difference? 
I don't see 
</blockquote></details>

I think num might be different than reads
___
*[bench/db_bench.cc, line 511 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUI9oRd-S2-IpbomJW3:-MUI9oRd-S2-IpbomJW4:b-1wan4i) ([raw file](https://github.com/pmem/pmemkv-bench/blob/7eb0b5fcddc87249fba36bb0fa67225700ee497b/bench/db_bench.cc#L511)):*
> ```cpp
> 		auto now = std::time(NULL);
> 		constexpr int time_string_size = std::strlen("01/01/21 12:37:50\n");
> 		char formatted_time[time_string_size];
> ```

shouldn't you add 1 to this size (for null terminator?) Or even better, there is something which does not require prededining a buffer: https://en.cppreference.com/w/cpp/io/manip/put_time 


<!-- Sent from Reviewable.io -->

2021-02-24 15:35 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor and @karczex)

___
*[bench/db_bench.cc, line 545 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAuF_RBQPTk1ZbgS3O:-MUJdFcO40GedvHL03NT:b-er10av) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L545)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think num might be different than reads
</blockquote></details>

When? I look on the initialization part. 
Maybe should we group this variables in structure:
```cpp
struct {
    char character = 'a';
    string any_string = "any_string_value";
    uint64_t num = 42;
} PredefinedValues;
```
On start, parse arguments, setup values and pass it to benchmark class.


<!-- Sent from Reviewable.io -->

2021-03-02 12:04 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[bench/db_bench.cc, line 545 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAuF_RBQPTk1ZbgS3O:-MUmofi_3eYVcGLZGcB7:b1twx2r) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L545)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

When? I look on the initialization part. 
Maybe should we group this variables in structure:
```cpp
struct {
    char character = 'a';
    string any_string = "any_string_value";
    uint64_t num = 42;
} PredefinedValues;
```
On start, parse arguments, setup values and pass it to benchmark class.
</blockquote></details>

Here: `reads_(FLAGS_reads < 0 ? FLAGS_num : FLAGS_reads)`


<!-- Sent from Reviewable.io -->

2021-03-02 12:05 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[bench/db_bench.cc, line 545 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUAuF_RBQPTk1ZbgS3O:-MUmolG06ZRKFuaG7NqR:b-iz84ya) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L545)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Here: `reads_(FLAGS_reads < 0 ? FLAGS_num : FLAGS_reads)`
</blockquote></details>

I pasted the wrong line ;d There are separate options for num and reads, those are different in e.g. readrandomwriterandom


<!-- Sent from Reviewable.io -->

2021-03-03 11:23 UTC, karczex commented
___
*[bench/db_bench.cc, line 511 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MU8csis8acUMf6ZVB7t:-MUrov8t36tEJmLb32oA:biggcq3) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0715c1dd427ce543e4e7ea09286b796bb4a48be0/bench/db_bench.cc#L511)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

don't we need the date for mongoCharts? shouldn't we break if this parsing fails?
</blockquote></details>

I don't think, we should fail benchmarking process if date conversion fails. 


<!-- Sent from Reviewable.io -->

2021-03-03 11:24 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: 0 of 1 files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[bench/db_bench.cc, line 511 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-MUI9oRd-S2-IpbomJW3:-MUro5qRDXQgRq0VT9Zl:b-t9oa4k) ([raw file](https://github.com/pmem/pmemkv-bench/blob/7eb0b5fcddc87249fba36bb0fa67225700ee497b/bench/db_bench.cc#L511)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't you add 1 to this size (for null terminator?) Or even better, there is something which does not require prededining a buffer: https://en.cppreference.com/w/cpp/io/manip/put_time 
</blockquote></details>

That's pretty good point. I  Added separate `insert(std::string column, time_t time )` overload to logger. And used put_time. 


<!-- Sent from Reviewable.io -->

2021-03-03 12:42 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61#-:-MUs62sv463Tvq1unkqS:bnfp4nl)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-03 13:13 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/61)* status: all files reviewed, 16 unresolved discussions (waiting on @karczex and @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-03 13:26 UTC, merged